---
- name: install, uninstall software and configure simple software on ubuntu server
  hosts: test
  become: true
  tasks:
    
    - name: install apache server
      apt: pkg=apache2 state=latest update_cache=true
    - name: service get started
      service:
              name: apache2
              state: started
    - name: uninstall wget server from remote
      apt:
             pkg: wget
             state: absent
             update_cache: true
