---
- name: simple playbook to create user on all host
  become: true
  hosts: test
  tasks:
   - name: creating a user named Ankit
     users:
      name: Ankit
      shell: /bin/bash
      password: "{{ 'password' | password_hash('sha512')}}"
      state: present 
